apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-dev-backend-apps
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/rvinnie/argocd
    path: argo-config/dev/backend
    targetRevision: main
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true