apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: init
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: https://github.com/rvinnie/argocd
      path: charts/base-service
      targetRevision: main
      helm:
        valueFiles:
          - values.yaml
          - /environments/dev/backend/services/init/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: qrcats-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true