apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.environment }}-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- if .Values.frontend.ingress.annotations }}
    {{- toYaml .Values.frontend.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.frontend.ingress.host }}
      secretName: {{ .Values.environment }}-frontend-ingress-secret
  ingressClassName: nginx
  rules:
    - host: {{ .Values.frontend.ingress.host }}
      http:
        paths:
        {{- range $svcName, $config := .Values.frontend.services }}
          - path: {{ $config.path }}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $svcName }}-frontend-service
                port:
                  number: 80
        {{- end }}