replicaCount: 2

service:
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

image:
  repository: registry.qrcats.ru/qrcats/dev/init-backend-service
  tag: sha256:bdb9378d42adab489ba711326674b6acdffb7ae1e7bc2a27720894346c227783