apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-frontend-init2
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: https://github.com/rvinnie/argocd
      path: charts/base-service
      targetRevision: main
      helm:
        valueFiles:
          - values.yaml
          - /environments/prod/frontend/services/init2/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: qrcats-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
